
services:
  db:
    image: postgres:16
    container_name: pg16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: springboot_app_dev
    ports:
      - "8080:8080"
      - "5005:5005"   # opsional: remote debug
    volumes:
      - ./:/app       # mount seluruh project
      - ~/.m2:/root/.m2  # cache maven host -> cepat
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    command: ["./mvnw","spring-boot:run","-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
    depends_on:
      - db
volumes:
  pgdata:
