# Dockerfile.dev
FROM eclipse-temurin:17-jdk
WORKDIR /app

# copy wrapper & pom dulu biar cache dependencies
COPY .mvn .mvn
COPY mvnw .
COPY pom.xml .

RUN chmod +x mvnw && ./mvnw -q -DskipTests dependency:go-offline

# src tidak di-COPY, nanti di-mount dari host
EXPOSE 8080 5005
CMD ["./mvnw","spring-boot:run"]
