## nama aplikasi 
spring.application.name=demo

## url konkesi ke postgreSQL di dalam docker-compose
spring.datasource.url=jdbc:postgresql://db:5432/appdb
spring.datasource.username=postgres
spring.datasource.password=postgres

## HIbernate (ORM) config update digunakna untuk update enity 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
